// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3DLizuuR1IUNwvC_T3jwkcsXu7sQLEI8',
    appId: '1:154558251344:web:228c3802236daa5003ec55',
    messagingSenderId: '154558251344',
    projectId: 'diaspora-app-9ffb9',
    authDomain: 'diaspora-app-9ffb9.firebaseapp.com',
    storageBucket: 'diaspora-app-9ffb9.appspot.com',
    measurementId: 'G-Z5SPRFPK2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJFGsuTVQJM-rsCgdlBnqhFslH9APeJA',
    appId: '1:154558251344:android:9786690289de60cd03ec55',
    messagingSenderId: '154558251344',
    projectId: 'diaspora-app-9ffb9',
    storageBucket: 'diaspora-app-9ffb9.appspot.com',
  );
}
